### ISSUE TITLE
Script not working properly?

### ISSUE THREAD

**Issue by ERFouX** [ItsTerm1n4l/dotfiles#1]
![Uploading Screenshot_2024-06-24_14-26-27.png…]()

I ran the script and logged out/logged in after it finished

**Comment by ERFouX** [comment]
![Screenshot_2024-06-24_14-26-27](https://github.com/ItsTerm1n4l/dotfiles/assets/138167877/0e1770d9-7518-4f16-843f-ad74f8ee4eee)

**Comment by ItsTerm1n4l** [comment]
Sorry, I didn't see this earlier. Anyway.
1. I forgot to include fonts in the dotfiles, you can look at the xfce4-terminal and eww configs and change the font settings, or you can download the necessary fonts manually.
2. The dotfiles can also be installed manually. 
first cd into the dotfiles directory, then:
```
cp -r ./.config/* ~/.config/
mkdir ~/.themes
cp -r ./.themes/* ~/.themes
mkdir ~/.icons
cp -r ./.icons/* ~/.icons
mkdir ~/.local/bin
cp -r ./.local/bin ~/.local/bin
```
or you can simply do this from the file manager
3. I didn't make this clear enough in the README but you do need to install these `xfce-terminal fish nautilus eww plank` packages if you are on debian or raspberry pi os the command would be `sudo apt install xfce-terminal fish nautilus eww plank`.

These dotfiles are old now and I am no longer using them, but I will update this repo and make instructions more clear.
I'm not sure from your screenshot if the script has worked or not, if it has you will not need step **2.**. but you might want to check if it has failed partway although I cant see any reason why it should.

Oh and also you will need to set the gtk theme and icon theme to the ones you have installed, this can be done with the xfce appearance manager
or with 
```
gsettings set org.gnome.desktop.interface icon-theme 'Zafiro'
gsettings set org.gnome.desktop.interface gtk-theme 'London-night'
```
and if you are trying to get a similar end result to my screenshot you will want to disable xfce-panel.
Thank you for your patience and feel free to ask any more questions!

**Comment by ERFouX** [comment]
thank you :D
